const datainfo = `[
    {"id":1,
    "title":"iPhone 9",
    "description":"An apple mobile which is nothing like apple 9",
    "price":549,
    "discountPercentage":12.96,
    "rating":4.69,"stock":94,
    "brand":"Apple",
    "category":"smartphones",
    "link": "#",
    "thumbnail":"https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
    "images":["https://cdn.dummyjson.com/product-images/1/1.jpg",
    "https://cdn.dummyjson.com/product-images/1/2.jpg",
    "https://cdn.dummyjson.com/product-images/1/3.jpg",
    "https://cdn.dummyjson.com/product-images/1/4.jpg",
    "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg"]},
    {"id":2,
    "title":"iPhone 10",
    "description":"An apple mobile which is nothing like apple 10",
    "price":560,
    "discountPercentage":12.96,
    "rating":4.69,"stock":96,
    "brand":"Apple",
    "category":"smartphones",
    "link": "#",
    "thumbnail":"https://cdn.dummyjson.com/product-images/1/4.jpg",
    "images":["https://cdn.dummyjson.com/product-images/1/1.jpg",
    "https://cdn.dummyjson.com/product-images/1/2.jpg",
    "https://cdn.dummyjson.com/product-images/1/3.jpg",
    "https://cdn.dummyjson.com/product-images/1/4.jpg",
    "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg"]},
    {"id":3,
    "title":"iPhone 12",
    "description":"An apple mobile which is nothing like apple 12",
    "price":600,
    "discountPercentage":12.96,
    "rating":4.69,"stock":98,
    "brand":"Apple",
    "category":"smartphones",
    "link": "#",
    "thumbnail":"https://cdn.dummyjson.com/product-images/1/3.jpg",
    "images":["https://cdn.dummyjson.com/product-images/1/1.jpg",
    "https://cdn.dummyjson.com/product-images/1/2.jpg",
    "https://cdn.dummyjson.com/product-images/1/3.jpg",
    "https://cdn.dummyjson.com/product-images/1/4.jpg",
    "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg"]},
    {"id":4,
    "title":"iPhone 12 pro",
    "description":"An apple mobile which is nothing like apple 12 pro",
    "price":700,
    "discountPercentage":12.96,
    "rating":4.69,"stock":94,
    "brand":"Apple",
    "category":"smartphones",
    "link": "#",
    "thumbnail":"https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
    "images":["https://cdn.dummyjson.com/product-images/1/1.jpg",
    "https://cdn.dummyjson.com/product-images/1/2.jpg",
    "https://cdn.dummyjson.com/product-images/1/3.jpg",
    "https://cdn.dummyjson.com/product-images/1/4.jpg",
    "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg"]},
    {"id":5,
    "title":"iPhone 15",
    "description":"An apple mobile which is nothing like apple 15",
    "price":760,
    "discountPercentage":12.96,
    "rating":4.69,"stock":96,
    "brand":"Apple",
    "category":"smartphones",
    "link": "#",
    "thumbnail":"https://cdn.dummyjson.com/product-images/1/4.jpg",
    "images":["https://cdn.dummyjson.com/product-images/1/1.jpg",
    "https://cdn.dummyjson.com/product-images/1/2.jpg",
    "https://cdn.dummyjson.com/product-images/1/3.jpg",
    "https://cdn.dummyjson.com/product-images/1/4.jpg",
    "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg"]},
    {"id":6,
    "title":"iPhone 16 pro",
    "description":"An apple mobile which is nothing like apple 16 pro",
    "price":900,
    "discountPercentage":12.96,
    "rating":4.69,"stock":98,
    "brand":"Apple",
    "category":"smartphones",
    "link": "#",
    "thumbnail":"https://cdn.dummyjson.com/product-images/1/3.jpg",
    "images":["https://cdn.dummyjson.com/product-images/1/1.jpg",
    "https://cdn.dummyjson.com/product-images/1/2.jpg",
    "https://cdn.dummyjson.com/product-images/1/3.jpg",
    "https://cdn.dummyjson.com/product-images/1/4.jpg",
    "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg"]}
    ]`